### PR TITLE
Add a license

### PR DESCRIPTION
**Pull request by rkaminsk**
Hello, I forgot to add a license (MIT) to the project and want to do this now. If you are okay with this PR, please add a comment:

- @stefanogermano 
- @sthiele 
- @tortinator 
- @MaxOstrowski 
- @pobermei 
- @wanko 
- @javier-romero 
- @pluehne 
- @cschulz-hanke 
- @BenKaufmann 
- @mgebser

### CODE REVIEW

**Comment by tortinator** [comment]
Fine with me too :+1:

**Comment by sthiele** [comment]
This is for the website? then wouldn't a CC license be more appropriate? 
https://creativecommons.org/about/cclicenses/

**Comment by rkaminsk** [comment]
> This is for the website? then wouldn't a CC license be more appropriate? https://creativecommons.org/about/cclicenses/

I thought about it. The MIT covers software + documentation. Since the website is kind of a software documentation, I thought it would be fine. In the end it just says use at your own risk plus some minor restrictions when using in another project.

**Comment by BenKaufmann** [comment]
MIT :+1:

**Comment by cschulz-hanke** [comment]
Fine by me.

**Comment by MaxOstrowski** [comment]
Fine

**Comment by javier-romero** [comment]
Fine with me.

**Comment by stefanogermano** [comment]
That is fine with me too

**Comment by wanko** [comment]
Fine with me.

**Comment by mgebser** [comment]
Fine with me.

**Comment by rkaminsk** [comment]
I think we have everyone. Thanks!

**Pull request merged**
