### PR TITLE
bc2asp renamed to coala, appended old coala

### PR DESCRIPTION
**Pull request by cschulz-hanke**
bc2asp renamed to coala, appended old coala

### CODE REVIEW

**Comment by rkaminsk** [comment]
Would you please convert the page to markdown. As far as I can see markdown directly supports everything you need. Should only take a couple of minutes.

**Comment by cschulz-hanke** [comment]
Done.
I don't quite see why that is required though.

**Comment by rkaminsk** [comment]
On Wednesday, January 11, 2017 2:31:34 AM CET Christian wrote:
> Done.
> I don't quite see why that is required though.
Markdown is much easier to maintain. Your html might make problem when 
switching themes (just look at the preview on github), etc. Also all the other 
pages are written in markdown.

A few more things:

Headlines automatically get anchors. Say you want to have a link to the 
Content heading: [Content](#content)

Can you remove all the ugly <br>s.

In markdown **word** should be used instead of <b>word</b>

-R

**Comment by cschulz-hanke** [comment]
Done.

**Pull request merged**
