### PR TITLE
Update asprilo page

### PR DESCRIPTION
**Pull request by pobermei**

### CODE REVIEW

**Comment by rkaminsk** [comment]
Looks good. Just two small things you might want to address:

- On other pages, we explicitly put some publications under the headline citing. This way, you can tell people which paper you want them to cite if they are using your tool.
- You should use `{{ site.publicationurl }}` to link to the publications. You can also use `{{ site.publicationurl }}/#DBLP_journals/corr/abs-1804-10247` to highlight an entry in the list. Check [clingo.md](https://github.com/potassco/potassco.github.io/blob/master/clingo.md) for an example.

I put also @tortinator in the loop because he came up with the citing thing.

PS: There is also a [deploy preview](https://deploy-preview-22--potassco.netlify.com/asprilo/).

**Comment by tortinator** [comment]
Hi, I guess it's important to supply publications and citations with our work.

@rkaminsk : Why do we have both "Publications" and "Citing" with Clingo?
I forgot why... Perhaps the former is enough..?
Also, we should switch from the CoRR citation to the TPLP that just appeared this year.

**Comment by rkaminsk** [comment]
I always thought of citing as the publications you want people to cite and publications just extra information. I am not sure how exactly this grew. Just tell me how you want this page to look and I adjust. :smile:

**Comment by tortinator** [comment]
You're right, and I have to think about it; with clasp it made sense this way, since there were lots of pubses but here ... mmmh

**Pull request merged**
