### PR TITLE
Update clingo-module.js

### PR DESCRIPTION
**Pull request by stefnotch**
Untested fix for #41

### CODE REVIEW

**Comment by rkaminsk** [comment]
> Untested fix for #41

Thanks, you can check here if it is working for you: <https://deploy-preview-43--potassco.netlify.app/>.

**Comment by stefnotch** [comment]
Lovely, it works

**Comment by rkaminsk** [comment]
One last thing before I merge. Is it okay to publish the change under MIT license? I forgot to add license before and now have to ask.

**Comment by stefnotch** [comment]
Sure

**Pull request merged**
