### PR TITLE
Use WebAssembly version of Clingo 

### PR DESCRIPTION
**Pull request by domoritz**
Compiled with https://github.com/Aluriak/webclingo-example. This version faster than the previous version.

Try it out at https://www.domoritz.de/potassco.github.io/clingo/run/ (note that you have to copy+paste examples manually as the domain isn't correct).

### CODE REVIEW

**Comment by rkaminsk** [comment]
I think I am going to stick with the asm.js version for a little longer. While the major browsers all support WebAssembly now, there might still be some where this is not the case. And after all this page is meant to be a getting started point - performance does not matter so much. At some point, I'll probably do the switch.

**Comment by rkaminsk** [comment]
I did a little more research and it seems like WebAssembly is supported as well as asm.js. Since emscripten compiles to WebAssembly by default now, the online version now uses it.

**Comment by domoritz** [comment]
:tada:

I've been using the wasn't version of clingo for a few months now and it works great and is really fast. I compiled it with optimizations, though.

**Comment by rkaminsk** [comment]
On Wednesday, June 27, 2018 1:49:24 PM CEST Dominik Moritz wrote:
> :tada:
> I've been using the wasn't version of clingo for a few months now and it
> works great and is really fast. I compiled it with optimizations, though.
I did too - optimized for size with -Os. -R

**Comment by domoritz** [comment]
I optimized for speed (using default release settings) and the file is 2.49 MB instead of 2.34 MB. The difference is quite small, which is great.

**Pull request closed without merging**
